### ISSUE TITLE
USER STORY: Publishing a Poll

### ISSUE THREAD

**Issue by Cesargarciajr** [Cesargarciajr/love-running#5]
In order to **automatically hide the poll** as a **administrator**, I can **pick the expiry date while pubishing the poll**

# Acceptance Criteria:

* The poll should disappear at 11:59 PM on the target date.
* The real estate of the "Poll" should be reserved on the home page. a message that says "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
* The administrator expiry date should be at least 3 days after the current date.

# Tasks:

- [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionalitty
